### ISSUE TITLE
Basato.

### ISSUE THREAD

**Issue by Bavuett** [caamillo/bitmod#1]
Scusa per lo spam, non c'è la scheda discussion aperta.

Però basato.

**Comment by caamillo** [comment]
Aahahahaha grazie fra.

Ho notato inoltre che di recente TUA ha finalmente introdotto le API per sapere quando arriva il bus (non capisco se hanno messo un gps sui bus o un server che fa calcoli sulle distanze per tutto il tempo), se ti può interessare..

(POST) https://portal.bigosolutions.it/api/tracker/TUABRUZZO/forecast/stopId/1
(GET) https://portal.bigosolutions.it/stopuserinfo/stopuserinfo.html?code=BS-ta&stop=1

sullo `stopId` o `stop` puoi mettere le fermate da 1 a 373

Io fra poco ci faccio un front-end alternativo perchè mi serve..

**Comment by Bavuett** [comment]
Sì, non appena hanno lanciato la API ci ho fatto una shortcut sul mio iPhone e uso la API in quel modo.

È talmente una minchiata che non ho deciso di buttarci altro tempo, la Shortcut di iOS funziona benissimo. 

Riguardo al calcolo delle distanze penso sia semplicemente basato sul tempo e nient'altro, quindi immagino che abbiano un orario di inizio di servizio e tempo stimato di arrivo per ogni fermata. Sono giunto a questa conclusione perché in caso contrario sarebbe molto più preciso, a volte mi sono capitati anche 10 minuti di ritardo rispetto a quanto dichiara la API.

Magari per il front-end che evita di mettere gli ID collaboriamo :)

https://github.com/user-attachments/assets/b8882f0e-e8bd-4a59-b53d-01a6dbad7182

**Comment by caamillo** [comment]
Figata, non sapevo.
Comunque volentieri
